# Generated by Django 3.0.5 on 2020-05-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='index',
        ),
    ]
